#+begin_export latex
In this section we survey the distribution of the genomes among
species, especially bacterial species. We begin by counting the
2,844,193 taxa.
#+end_export
#+begin_src bash <<res.sh>>=
  q="select count(*)"
  q="$q from taxon"
  sqlite3 neidb "$q"
#+end_src
#+begin_export latex
We count the 2,319,400 species in \ty{neidb}.
#+end_export
#+begin_src bash <<res.sh>>=
  q="select count(*)"
  q="$q from taxon"
  q="$q where rank like 'species'"
  sqlite3 neidb "$q"
#+end_src
#+begin_export latex
We find the taxon-ID of bacteria, 2.
#+end_export
#+begin_src bash <<res.sh>>=
  taxi -e "bacteria" neidb
#+end_src
#+begin_export latex
\begin{verbatim}
# ID  Parent  Name
  2   131567  Bacteria
\end{verbatim}
#+end_export
#+begin_export latex
We store all bacterial taxa with their recursive counts of genomes
assembled to any level in file \ty{any.txt}. To facilitate further
processing, we convert the column delimiters, two blanks, to tabs, and
replace any remaining blanks by underscores. This takes 116\,s.
#+end_export
#+begin_src bash <<res.sh>>=
  dree -R -l 2 neidb |
      sed -E 's/  +/\t/g' |
      sed 's/ /_/g' > any.txt
#+end_src
#+begin_export latex
Similarly, we store all bacterial taxa with their recursive counts of
genomes assembled to level complete in file \ty{comp.txt}. This time
we also include the taxon names. This takes 69\,s.
#+end_export
#+begin_src bash <<res.sh>>=
  dree -R -l -L complete -n 2 neidb |
      sed -E 's/  +/\t/g' |
      sed 's/ /_/g' > comp.txt
#+end_src
#+begin_export latex
We would like to join our two tables of genome counts. For this we
remove the table headers and sort the tables.
#+end_export
#+begin_src bash <<res.sh>>=
  for a in any comp; do
      tail -n +2 $a.txt |
          sort > t
      mv t $a.txt
  done
#+end_src
#+begin_export latex
From the join we extract the taxon-ID, its rank, the genome count for
assembly levels any and complete, and the taxon name.
#+end_export
#+begin_src bash <<res.sh>>=
  join any.txt comp.txt |
      cut -d ' ' -f 1,3,4,7,8 > anyComp.txt
#+end_src
#+begin_export latex
We count the 549,008 bacterial species.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$2=="species"' anyComp.txt |
      wc -l
#+end_src
#+begin_export latex
There are 3,154,814 bacterial genomes assembled to any level, compared
to only 83,034 assembled to level complete.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$1==2' anyComp.txt
#+end_src
#+begin_export latex
The bacterial genomes make up 88.6\,\% of the total genome
count, 3,559,920.
#+end_export
#+begin_src bash <<res.sh>>=
  dree -m 0 -l -R 1 neidb 
#+end_src
#+begin_export latex
\begin{verbatim}
# Taxid  Parent  Rank     Genomes
1        1       no rank  3559920
\end{verbatim}
#+end_export
#+begin_export latex
There are 104,642 bacterial species with at least one genome sequence.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$2=="species" && $3 >= 1' anyComp.txt |
      wc -l
#+end_src
#+begin_export latex
There are just 17,012 bacterial species with at least one
\emph{complete} genome.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$2=="species" && $4 >= 1' anyComp.txt |
      wc -l
#+end_src
#+begin_export latex
We store the number of genomes per bacterial species with at least one
genome in \ty{gcAny.dat}.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$2=="species" && $3>0' anyComp.txt |
      awk '{c[$3]++}END{for(a in c)print a, c[a]}' |
      sort -n > gcAny.dat
#+end_src
#+begin_export latex
The most frequent genome count per species is 1, which occurs 84,977
times.
#+end_export
#+begin_src bash <<res.sh>>=
  head -n 1 gcAny.dat
#+end_src
#+begin_export latex
This means to 81.2\,\% of sequenced bacterial species have a single
genome.
#+end_export
#+begin_src bash <<res.sh>>=
  echo "84977 / 104642" | bc -l
#+end_src
#+begin_export latex
We store the number of complete genomes per bacterial species with at
least one genome in \ty{gcComp.dat}. This takes approximately 51\,s.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$2=="species" && $4>0' anyComp.txt |
      awk '{c[$4]++}END{for(a in c)print a, c[a]}' |
      sort -n > gcComp.dat
#+end_src
#+begin_export latex
The most frequent count of complete genomes per bacterial species is
also 1, which occurs 13,778.
#+end_export
#+begin_src bash <<res.sh>>=
  head -n 1 gcComp.dat
#+end_src
#+begin_export latex
This means 79.3\,\% of all bacterial species with one or more complete
sequenced genomes have just a single genome.
#+end_export
#+begin_src bash <<res.sh>>=
  echo "13778 / 17384 * 100" | bc -l
#+end_src
#+begin_export latex
The largest number of sequenced genomes of any assembly level is
618,721.
#+end_export
#+begin_src bash <<res.sh>>=
  tail -n 1 gcAny.dat
#+end_src
#+begin_export latex
This is the genome count for \emph{Salmonella enterica}.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$3==618721' anyComp.txt
#+end_src
#+begin_export latex
The largest number of sequenced genomes assembled to level complete is
7884.
#+end_export
#+begin_src bash <<res.sh>>=
  tail -n 1 gcComp.dat
#+end_src
#+begin_export latex
This is the genome count for \emph{Escherichia coli}.
#+end_export
#+begin_src bash <<res.sh>>=
  awk '$4==7884' anyComp.txt
#+end_src
