#+begin_export latex
Bacterial genome sequencing is now routine in many clinical
settings. To make the best use of the resulting wealth of sequence
data, it needs to be correctly classified. However, the vast majority
of bacterial strains are only classified down to the species rank,
which in many cases includes multiple commensal and pathogenic strains
that need to be distinguished for effective treatment and
surveillance.

The classification of bacterial genomes below the species rank is the
topic of our forthcoming manuscript entitled \textit{Classifying the
  Genomes of \emph{E. coli} strains}. In this accompanying
tutorial we show the required computations. Our focus is no
\emph{Escherichia coli}, one of the most intensively sequenced
bacterial taxa, which contains commensals and numerous well-known
pathogenic strains.

Taxa are labeled by taxon-IDs and we begin this tutorial by looking up
the taxon-ID of \emph{E. coli}. So if you now change into the
directory \ty{tutorial} inside the \ty{ecos} repository, we can use
the program \ty{taxi} in exact matching mode to find that the taxon-ID
of \emph{E. coli} is 562, that of its parent, the genus
\emph{Escherichia}, is 561.
#+end_export
#+begin_src bash <<intro.sh>>=
  taxi -e "Escherichia coli" neidb
#+end_src
#+begin_export latex
\begin{verbatim}
# ID   Parent  Name
  561  543     Escherichia
\end{verbatim}
#+end_export
#+begin_export latex
To get an overview of the \emph{E. coli} genomes currently available
in Genbank, we draw the tree of all ranks in that species and how many
genomes each one contains. Genomes are assembled to one of four
quality levels, complete, chromosome, scaffold, or conting, in that
order. We restrict our analysis to the ``best'' genomes, those
assembled to level ``complete''. The tree of complete genomes per rank
is specified in \ty{dot} notation, which we can render with the
program \ty{dot}, whose output can in turn be drawn with \ty{imv-x11}
to get Figure~\ref{fig:ranks}. It shows that 92.9\,\% of complete
\emph{E. coli} genomes are only classified at the species rank.
\begin{figure}
  \input{../intro/ranksLabels.tex}
  \begin{center}
    \resizebox{0.9\textwidth}{!}{\includegraphics{../intro/ranks}}
  \end{center}
  \caption{The distribution of complete genomes among the taxonomic
    ranks of \emph{E. coli}.}\label{fig:ranks}
\end{figure}
#+end_export
#+begin_src bash <<intro.sh>>=
  ranks -L complete 562 neidb |
      dot -T svg |
      imv-x11 -
#+end_src
#+begin_export latex
The ranks in the tree in Figure~\ref{fig:ranks} tell us little about
the distribution of genomes among specific strains. For this we use
\ty{dree} to list (\ty{-l}) the names (\ty{-n}) and the recursive
(\ty{-R}) counts of complete (\ty{-L}) genomes among the
\emph{E. coli} taxa listed with names (\ty{-n}). We extract the taxa
with at least 10 genomes to get a table similar to
Table~\ref{tab:taxa}.
\begin{table}
  \caption{The eight \emph{E. coli} taxa with \emph{initially} at
    least 10 complete genomes in Genbank; the \emph{final} genome
    count refers to the number of genomes in the clade rooted on
    \emph{node} in the phylogeny of all complete \emph{E. coli}
    genomes analyzed (\ty{eco2.nwk}); table ordered by initial genome
    count.}\label{tab:taxa}
  \begin{center}
    \resizebox{\textwidth}{!}{
      \begin{tabular}{crllrrlr}
        \hline
        &&&&\multicolumn{2}{c}{Genomes}\\\cline{5-6}
        \# & Taxon-ID & Parent & Rank & Initial & Final & Name & Node\\\hline
        \input{../intro/taxa}\\\hline
      \end{tabular}
    }
  \end{center}
\end{table}
#+end_export
#+begin_src bash <<intro.sh>>=
  dree -n -R -L complete -l 562 neidb |
      tail -n +2 |
      sed 's/o /o_/' |
      sort -k 4 -n -r |
      awk '$4>=10'
#+end_src
#+begin_export latex
As shown in Table~\ref{tab:taxa}, there are 7,884 complete
\emph{E. coli} genomes. Notorious pathogen O157:H7 is the strain with
most sequenced genomes, 171, followed by the commensal K-12 taxon
83333 with 65 genomes. These 65 genomes contain the 29 genomes of its
K-12 child taxon 511145. The two bracketed K-12 entries in
Table~\ref{tab:taxa} are followed by four well-known pathogens,
O111:H8, O25b:H4-ST131, O16:H48, and O145 with a combined 69 genomes.

Analyzing the 7,884 \emph{E. coli} genomes takes perhaps an hour. And
while this is quick considering the amounts of data involved, any
computational workflow with this kind of run time is difficult to
construct, amend, and maintain.

We therefore continue this tutorial in Chapter~\ref{ch:p} with a pilot
study on how to construct a phylogeny from a sample of 50 complete
\emph{E. coli} genomes that contains the 22 O111:H8 genomes listed in
line 5 of Table~\ref{tab:taxa} and 28 closely related genomes.

In Chapter~\ref{ch:q} we show how to query a precomputed phylogeny of
all \emph{E. coli} genomes to identify the complete sample of
available O111:H8 genomes. This complete sample turns out to contain
not only the original 22 O111:H8, but an additional 25 genomes,
yielding a total of 47 O111:H8 genomes (Table~\ref{tab:taxa}).

In addition to O111:H8, we also query the complete tree for the other
five distinct taxa below species rank listed in Table~\ref{tab:taxa},
O157:H7, K-12, O25b:H4-ST131, O16:H48, and O145. Like for O111:H8, we
find additional genomes for four of these five taxa.

In Chapter~\ref{ch:m}, finally, the 47 genomes of \emph{E. coli}
O111:H8 identified in Chapter~\ref{ch:q} are used to construct
diagnostic PCR primers for that serotype.
#+end_export
