#+begin_export latex
Again, our working directory is \ty{tutorial} inside the \ty{o111h8}
repo. We count the 7,386 complete genomes in the \emph{E. coli} tree
by picking its root, node 1, and counting the listed leaves.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco.nwk |
      grep -c -v '^#'
#+end_src
#+begin_export latex
Since bacterial species are defined as having an ANI distance of at
least 95, we measure the largest distance in our tree, 0.0672.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_022654545.1, 562_GCF_021307345.1): 0.0672
\end{verbatim}
A distance of 0.0672 implies an ANI of 93, which is below the 95 ANI
threshold for bacterial species. This suggests our current sample
contains at least one genome that does not belong to
\emph{E. coli}. To investigate further, we climb from the two most
distant taxa towards the root of the phylogeny. The climb from
\begin{verbatim}
562_GCF_022654545.1
\end{verbatim}
consists of 72 steps, indicating many short branches on the way.
#+end_export
#+begin_src sh <<query.sh>>=
  climt 562_GCF_022654545.1 eco.nwk |
      head -n 2
#+end_src
#+begin_export latex
\begin{verbatim}
#Up Node  BranchLength  CumulativeBranchLength
72  1     0             0.0335740797
\end{verbatim}
#+end_export
#+begin_export latex
In contrast, the climb from
\begin{verbatim}
562_GCF_021307345.1
\end{verbatim}
consists of a single step.
#+end_export
#+begin_src sh <<query.sh>>=
  climt 562_GCF_021307345.1 eco.nwk |
      head -n 2
#+end_src
#+begin_export latex
We remove that taxon and relabel the internal nodes of the resulting
tree.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle -t -c 562_GCF_021307345.1 eco.nwk |
      land > eco2.nwk
#+end_src
#+begin_export latex
The most distant genomes in our \emph{E.~coli} sample now have ANI 96,
which fits the species criterion.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco2.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_057180125.1, 562_GCF_022654545.1): 0.0394
\end{verbatim}
We can next determine the taxa with complete genomes that belong to
the taxonomic subtree rooted on 991910. We use the program
\ty{neighbors} for this, which shows there is only one taxon in the
subtree rooted on 991910, 991910 itself.
#+end_export
#+begin_src sh <<query.sh>>=
  neighbors -L complete -t 991910 -o -l neidb |
      grep -v '^#' |
      awk '{print $3}' |
      sort |
      uniq 
#+end_src
#+begin_export latex
We count the 22 genomes on the tree classified as O111:H8.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco2.nwk |
      grep -c 991910_
#+end_src
#+begin_export latex
We use \ty{fintac} to find the clade with the largest split between
O111:H8 genomes and the rest. By default, any taxon that is not a
target is classified as neighbor. However, we can use \ty{-u} to
assert that taxa classified as \emph{E.~coli} are ``unknown''. In this
way we find clade 4649, which contains not only our 22 targets, but in
addition 8 neighbors and 17 unknowns.
#+end_export
#+begin_src sh <<query.sh>>=
  fintac -t 991910_ -u 562_ eco2.nwk
#+end_src
#+begin_export latex
\begin{verbatim}
#Clade  Targets  Neighbors  Unknowns  Split (%)  Parent  Dist(Parent)
4649    22       8          17        98.53      4647    0.000465
\end{verbatim}
To put our target clade in context, we plot the subtree rooted on its
parent, 4647, without the labels of the internal nodes.
Figure~\ref{fig:all} shows this tree with the \emph{E. coli} O111:H8
genomes marked $T$ for \emph{target}, its two closest relatives marked
$N$ for \emph{neighbors}, and the node with the highest split score
originally picked by \ty{fintac} marked $S$.
\begin{figure}
  \begin{center}
    \rput(3.8,1.7){$T$}
    \rput(3.8,0.6){$N$}
    \includegraphics{../query/eco2}
  \end{center}
  \caption{The 47 complete target genomes of \emph{Escherichia coli}
    O111:H8, $T$, in the context of its closest relatives, the two
    neighbors in clade $N$.}\label{fig:all}
\end{figure}
#+end_export
#+begin_src sh <<query.sh>>=
  pickle -t 4647 eco2.nwk |
      land -r |
      plotTree
#+end_src
#+begin_export latex
We count 47 complete genomes in clade 4649. This means we have
discovered 25 candidate O111:H8 genomes.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 4649 eco2.nwk |
      grep -v '^#' -c
#+end_src
#+begin_export latex
To check the true serotype of the candidate genomes, we join the 47
genomes in clade 4649 to the serotype list in \ty{sero.txt}. This
shows that indeed all 47 genomes in clade 4649 have are O111:H8. In
other words, we have discovered and additional 25 genomes that were
not classified as O111:H8.

Let's take a closer at the taxa in our target clade. Apart from the 22
O111:H8 genomes, we find 18 \emph{E. coli} (562). We shall look up the
remaining five taxon-IDs in a moment.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 4649 eco2.nwk |
    grep -v '^#' |
    tr '_' ' ' |
    awk '{print $1}' |
    sort |
    uniq -c |
    sort -n -r
#+end_src
#+begin_export latex
\begin{verbatim}
     22 991910
     17 562
      4 373045
      1 585396
      1 397453
      1 168927
      1 1055542
\end{verbatim}
The remaining five taxa are all classified as serotype O111, which is
reassuring, albeit not O111:H8.
#+end_export
#+begin_src sh <<query.sh>>=
  for a in 373045 585396 397453 168927 1055542; do
      echo "# $a"
      ants $a neidb |
	  tail -n 2
  done
#+end_src
#+begin_export latex
\begin{verbatim}
# 373045
  1     562      Escherichia coli          species
  0     373045   Escherichia coli O111:NM  no rank
...
\end{verbatim}

This means that \textit{E.coli} O111:NM is the serotype that has most
frequently been mistaken for O111:H8. The full description of the
taxon IDs and their corresponding names is shown in Table
\ref{tbl:O111types}.

\begin{table}[h]
  \begin{center}
    \caption{Composition of the O111:H8 target clade.}
    \label{tbl:O111types}
    \begin{tabular}{rlr}
      \hline
      Taxon ID & Name & Count \\
     \hline
      991910  & \textit{Escherichia coli} O111:H8 & 22\\
      562     & \textit{Escherichia coli} & 17\\
      373045  & \textit{Escherichia coli} O111:NM & 4\\
      168927  & \textit{Escherichia coli} O111:H- & 1\\
      397453  & \textit{Escherichia coli} O111:H2 & 1\\
      585396  & \textit{Escherichia coli} O111:H- str. 11128 & 1\\
      1055542 & \textit{Escherichia coli} O111 str. RM9322 &1 \\
      \hline
    \end{tabular}
  \end{center}
\end{table}
#+end_export
#+begin_export latex
We've reached the end of the query section, so we remove three of the
four files we have produced, but leave \ty{eco2.nwk} for further
reference.
#+end_export
#+begin_src sh <<query.sh>>=
  rm neidb t1.txt t2.txt
#+end_src
