#+begin_export latex
\section{Finding and Filtering \emph{E. coli} Genomes}
Again, our working directory is \ty{tutorial} inside the \ty{ecos}
repo. In Table~\ref{tab:taxa} we already noted that there are 7884
complete \emph{E. coli} genomes. We get the accessions for these and
store them in \ty{eco.txt}.
#+end_export
#+begin_src sh <<query.sh>>=
  neighbors -t 562 -o -l -L complete neidb |
      tail -n +2 |
      awk '{print $2}' > eco.txt
#+end_src
#+begin_export latex
We make sure \ty{eco.txt} really contains 7884 genome accessions.
#+end_export
#+begin_src sh <<query.sh>>=
  wc -l eco.txt
#+end_src
#+begin_export latex
We get the genome summaries for these 7884 genomes and store them in
JSON format in a temporary file, \ty{tmp.json}.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets summary genome accession \
	   --inputfile eco.txt \
	   --as-json-lines > tmp.json
#+end_src
#+begin_export latex
To keep this tutorial stable, we switch to the summary file of 17th
Juni 2026, \ty{eco.json}. From this we pick the accessions where the
annotation notes do not contain the word ``fail'', the attribute
``atypical'' is not true, no rRNA or tRNA genes are missing, and
proteins have been frameshifted, and the ANI check has not failed.
#+end_export
#+begin_src sh <<query.sh>>=
  fields="'acc*','*notes','*atypical*','ani-check*'"
  dataformat tsv genome \
  	     --inputfile eco.json \
  	     --fields $fields |
      tail -n +2 |
      grep -v fail |
      grep -v true |
      grep -v missing |
      grep -v frameshifted |
      grep -v Failed |
      cut -f 1 > eco.txt
#+end_src
#+begin_export latex
The file \ty{eco.txt} now contains 7361 accessions, down by 523 from
the original 7884.
#+end_export
#+begin_src sh <<query.sh>>=
  wc -l eco.txt
#+end_src
#+begin_export latex
The next few commands form a ``bridge'' between the accessions and the
phylogeny. If you don't have the resources or the patience to download
the genomes and compute the phylogeny, you can directly skip ahead to
the phylogeny in the next \ty{query.sh} chunk. As a first step on the
bridge, we download the 7361 genomes in \ty{eco.txt}, first in
dehydrated form.
#+end_export
#+begin_src sh <<bridge>>=
  datasets download genome accession \
	   --inputfile eco.txt \
	   --dehydrated
#+end_src
#+begin_export latex
Then we unzip the dehydrated sequences and rehydrate them.
#+end_export
#+begin_src sh <<bridge>>=
  unzip ncbi_datasets.zip
  datasets rehydrate --directory .
#+end_src
#+begin_export latex
Before we construct the phylogeny, we link all genomes into the
directory \ty{all}, which we make.
#+end_export
#+begin_src sh <<bridge>>=
  mkdir all
#+end_src
#+begin_export latex
Like in the pilot, we rename the input files by running
\ty{rename.sh}. This takes about 1.5 minutes.
#+end_export
#+begin_src sh <<bridge>>=
  bash rename.sh
#+end_src
#+begin_export latex
We calculate the pairwise distances from the renamed genomes, convert
them to a neighbor-joining tree, midpoint root the tree, label its
internal nodes, and store it in \ty{eco.nwk}.
#+end_export
#+begin_src bash <<bridge>>=
  phylonium all/* |
      nj |
      midRoot |
      land > eco.nwk
#+end_src
#+begin_export latex
We count the 7,361 complete genomes in \ty{eco.nwk} by picking its
root, node 1, and counting the listed leaves.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco.nwk |
      grep -c -v '^#'
#+end_src
#+begin_export latex
Bacterial species are defined as having an ANI distance of at least
95. To check we are dealing only with \emph{E.~coli}, we measure the
largest distance between two taxa in our phylogeny, 0.0391.  This
corresponds to an ANI of 96.1, which fits the species criterion.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco2.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_057180125.1, 562_GCF_022654545.1): 0.0391
\end{verbatim}

We now query our grand \emph{E. coli} tree for the six taxa directly
below the species rank listed in Table~\ref{tab:taxa} following the
order in that table.

\section{\emph{E. coli} O157:H7 (83334)}\label{sec:o157h7}
\input{o157h7}
\section{\emph{E. coli} K-12 (83333)}\label{sec:k12}
\input{k12}
\section{\emph{E. coli} O111:H8 (991910)}\label{sec:o111h8}
\input{o111h8}
\section{\emph{E. coli} O25b:H4-ST131 (941322)}\label{sec:o25bh4}
\input{o25bh4}
\section{\emph{E. coli} O16:H48 (2605619)}\label{sec:o16h48}
\input{o16h48}
\section{\emph{E. coli} O145 (1055538)}\label{sec:o145}
\input{o145}
#+end_export
