#+begin_export latex
Again, our working directory is \ty{tutorial} inside the \ty{o111h8}
repo. We count the 7,386 complete genomes in the precomputed
\emph{E. coli} tree, \ty{eco.nwk}, by picking its root, node 1, and
counting the listed leaves.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco.nwk |
      grep -c -v '^#'
#+end_src
#+begin_export latex
Bacterial species are defined as having an ANI distance of at least
95. To check we are dealing only with \emph{E.~coli}, we measure the
largest distance between two taxa in our phylogeny, 0.0672.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_022654545.1, 562_GCF_021307345.1): 0.0672
\end{verbatim}
A distance of 0.0672 implies an ANI of 93, which is below the 95 ANI
threshold for bacterial species. This suggests our current sample
contains at least one genome that does not belong to
\emph{E. coli}. To investigate further, we climb from the two most
distant taxa towards the root of the phylogeny. The climb from
$\ast\mbox{022654545.1}$ consists of 72 steps, indicating many
short branches on the way.
#+end_export
#+begin_src sh <<query.sh>>=
  climt 562_GCF_022654545.1 eco.nwk |
      head -n 2
#+end_src
#+begin_export latex
\begin{verbatim}
#Up Node  BranchLength  CumulativeBranchLength
72  1     0             0.0335740797
\end{verbatim}
#+end_export
#+begin_export latex
In contrast, the climb from $\ast\mbox{021307345.1}$ consists of a
single step.
#+end_export
#+begin_src sh <<query.sh>>=
  climt 562_GCF_021307345.1 eco.nwk |
      head -n 2
#+end_src
#+begin_export latex
\begin{verbatim}
#Up  Node  Branch Length  Cumulative Branch Length
1    1     0              0.0336
\end{verbatim}
We remove that taxon by picking the tree of its complement, and
relabel the internal nodes of the resulting tree.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle -t -c 562_GCF_021307345.1 eco.nwk |
      land > eco2.nwk
#+end_src
#+begin_export latex
The most distant genomes in our \emph{E.~coli} sample now have ANI 96,
which fits the species criterion.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco2.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_057180125.1, 562_GCF_022654545.1): 0.0394
\end{verbatim}

We count the 22 genomes on the tree classified as O111:H8.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco2.nwk |
      grep -c 991910_
#+end_src
#+begin_export latex
We use \ty{fintac} to find the clade with the largest split between
O111:H8 genomes and the rest. By default, any taxon that is not a
target is classified as neighbor. However, we can use \ty{-u} to
assert that taxa classified as \emph{E.~coli} are ``unknown''.
#+end_export
#+begin_src sh <<query.sh>>=
  fintac -t 991910_ -u 562_ eco2.nwk
#+end_src
#+begin_export latex
\begin{verbatim}
#Clade  Targets  Neighbors  Unknowns  Split (%)  Parent  Dist...
4649    22       8          17        98.53      4647    0.000465
\end{verbatim}

Since O111:H8 might have subtaxa, we repeat the \ty{fintac} run with
hierarchical matching. Under hierarchical matching a taxon that is in
the taxonomic subtree rooted on the target is also classified as a
target. So hierarchical matching requires the taxonomy information
contained in the Neighbors database. Hence the option for hierarchical
matching, \ty{-H}, takes \ty{neidb} as argument. In the case of
O111:H8 it makes no difference, but we have observed cases where it
does, e. g. O157:H7.
#+end_export
#+begin_src sh <<query.sh>>=
  fintac -t 991910_ -u 562_ -H neidb eco2.nwk
#+end_src
#+begin_export latex
To put our target clade in context, we plot the subtree rooted on its
parent, 4647, without the labels of the internal nodes.
Figure~\ref{fig:all} shows this tree with the putative O111:H8 genomes
marked $T$ for \emph{target}, and its two closest relatives marked $N$
for \emph{neighbors}.
\begin{figure}
  \begin{center}
    \rput(3.8,1.7){$T$}
    \rput(3.8,0.6){$N$}
    \includegraphics{../query/eco2}
  \end{center}
  \caption{The 47 complete target genomes of \emph{Escherichia coli}
    O111:H8, $T$, in the context of its closest relatives, the two
    neighbors in clade $N$.}\label{fig:all}
\end{figure}
#+end_export
#+begin_src sh <<query.sh>>=
  pickle -t 4647 eco2.nwk |
      land -r |
      plotTree
#+end_src
#+begin_export latex
We count 47 complete genomes in clade 4649, 22 known O111:H8 and 27 we
hypothesize also belong to the same serotype.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 4649 eco2.nwk |
      grep -v '^#' -c
#+end_src
#+begin_export latex
To check the serotypes of our target genomes, we extract the
accessions of the 47 genomes in clade 4649 and match it to the list of
serotypes: \ty{sero.txt}. This shows that indeed all 47 genomes in
clade 4649 have are O111:H8. In other words, we have discovered and
additional 25 genomes that were not classified as O111:H8.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 4649 eco2.nwk |
      grep -v '^#' > O111.txt

  grep -f O111.txt sero.txt
#+end_src
#+begin_export latex
\begin{verbatim}
168927_GCF_007990655.1 O111:H8
373045_GCF_005037805.1 O111:H8
373045_GCF_049569765.1 O111:H8
...
991910_GCF_050705825.1 O111:H8
\end{verbatim}

We've reached the end of the query section, so we remove the list of O111:H8 accessions.
#+end_export
#+begin_src sh <<query.sh>>=
rm O111.txt
#+end_src
