#+begin_export latex
\section{Finding, Filtering, and Counting \emph{E. coli} Genomes}
Again, our working directory is \ty{tutorial} inside the \ty{ecos}
repo. In Table~\ref{tab:taxa} we already noted that there are 7884
complete \emph{E. coli} genomes. We get the accessions for these and
store them in \ty{eco.txt}.
#+end_export
#+begin_src sh <<query.sh>>=
  neighbors -t 562 -o -l -L complete neidb |
      tail -n +2 |
      awk '{print $2}' > eco.txt
#+end_src
#+begin_export latex
We make sure \ty{eco.txt} really contains 7884 genome accessions.
#+end_export
#+begin_src sh <<query.sh>>=
  wc -l eco.txt
#+end_src
#+begin_export latex
We get the genome summaries for these 7884 genomes and store them in
JSON format in a temporary file, \ty{tmp.json}.
#+end_export
#+begin_src sh <<query.sh>>=
  datasets summary genome accession \
	   --inputfile eco.txt \
	   --as-json-lines > tmp.json
#+end_src
#+begin_export latex
To keep this tutorial stable, we switch to the summary file of 17th
June 2026, \ty{eco.json}. From this we pick the accessions where the
annotation notes do not contain the word ``fail'', the attribute
``atypical'' is not true, no rRNA or tRNA genes are missing, no
proteins have been frameshifted, and the ANI check has not failed.
#+end_export
#+begin_src sh <<query.sh>>=
  fields="'acc*','*notes','*atypical*','ani-check*'"
  dataformat tsv genome \
  	     --inputfile eco.json \
  	     --fields $fields |
      tail -n +2 |
      grep -v fail |
      grep -v true |
      grep -v missing |
      grep -v frameshifted |
      grep -v Failed |
      cut -f 1 > eco.txt
#+end_src
#+begin_export latex
The file \ty{eco.txt} now contains 7361 accessions, down by 523 from
the original 7884.
#+end_export
#+begin_src sh <<query.sh>>=
  wc -l eco.txt
#+end_src
#+begin_export latex
We are interested in the distribution of these 7361 genomes among the
taxa below the species rank. Specifically, we look for the taxa with
at least ten genomes. So we look up the taxon-ID for each genome,
discard 562, and store the remainder in file \ty{taxids.txt}.
#+end_export
#+begin_src bash <<query.sh>>=
  while read acc; do
      q="select taxid"
      q="$q from genome"
      q="$q where accession = '$acc'"
      taxid=$(sqlite3 neidb "$q")
      echo $taxid
  done < eco.txt |
      awk '$1!="562"' > taxids.txt
#+end_src
#+begin_export latex
We might be tempted at this point to count the distinct
accessions. This gives seven taxa with genome counts ranging from 160
to 11.
#+end_export
#+begin_src bash <<query.sh>>=
  sort taxids.txt |
      uniq -c |
      sort -n -r |
      awk '$1>=10{printf("%s\t%s\n", $2, $1)}' |
      cat -n
#+end_src
#+begin_export latex
\begin{verbatim}
     1	83334	160
     2	991910	22
     3	83333	20
     4	941322	19
     5	511145	19
     6	2605619	16
     7	1055538	11
\end{verbatim}
However, genomes per taxon include the genomes of the subtaxa. To get
this \emph{recursive} genome count, we look up the ancestors below
\emph{E. coli}, 562, for each of our taxon-IDs. We save the result in
\ty{taxids2.txt}.
#+end_export
#+begin_src bash <<query.sh>>=
  while read taxid; do
      ants $taxid neidb |
  	awk 'open{print $2}$2==562{open=1}'
  done < taxids.txt > taxids2.txt
#+end_src
#+begin_export latex
The genome counts we now get range from 170 to 11, so they differ from
the naïve counts we got above. They also differ from the counts in
Table~\ref{tab:taxa}, which we got with \ty{dree} directly from the
database.
#+end_export
#+begin_src bash <<query.sh>>=
  sort taxids2.txt |
      uniq -c |
      sort -n -r |
      awk '$1>=10{printf("%s\t%s\n", $2, $1)}' |
      cat -n
#+end_src
#+begin_export latex
\begin{verbatim}
     1	83334	170
     2	83333	50
     3	991910	22
     4	941322	19
     5	511145	19
     6	2605619	16
     7	1055538	12
\end{verbatim}
#+end_export
#+begin_export latex
Our list of seven taxa might contain hierarchical relationships. To
find out, we first save the list to the file \ty{focalTaxa.txt}.
#+end_export
#+begin_src bash <<query.sh>>=
  sort taxids2.txt |
      uniq -c |
      sort -n -r |
      awk '$1>=10{printf("%s\t%s\n", $2, $1)}' |
      cat -n > focalTaxa.txt
#+end_src
#+begin_export latex
For each of the focal taxa, we look up the ancestors below 562 and
count the distinct taxa we get. We find one taxon with a count greater
than 1, 83333. Its count of 2 indicates that one of the other six
members of the taxon list is a subtaxon of 83333.
#+end_export
#+begin_src bash <<query.sh>>=
  while read n taxid count; do
      ants $taxid neidb |
          awk 'open{print $2}$2==562{open=1}'
  done < focalTaxa.txt |
      sort |
      uniq -c |
      sort -n -r
#+end_src
#+begin_export latex
\begin{verbatim}
      2 83333
      1 991910
      1 941322
      1 83334
      1 511145
      1 2605619
      1 1055538
\end{verbatim}
#+end_export
#+begin_export latex
To find out which of our taxa is a subtaxon of 83333, we plot the
taxonomy rooted on 83333 to get Figure~\ref{fig:83333}. This shows
that 511145 is a subtaxon of 83333.
\begin{figure}
  \begin{center}
    \resizebox{\textwidth}{!}{\includegraphics{../query/83333}}
  \end{center}
  \caption{The taxonomy rooted on 83333 showing the taxa with
    sequenced genomes.}\label{fig:83333}
\end{figure}
#+end_export
#+begin_src bash <<query.sh>>=
  dree -g 83333 neidb |
      xdot -
#+end_src
#+begin_export latex
We remove taxon 511145 from our list of seven focal taxa and look up the
names of the remaining six to get Table~\ref{tab:foc}.
\begin{table}
  \caption{The taxa, genome counts, and names of our six focal taxa}\label{tab:foc}
  \begin{center}
    \begin{tabular}{clrl}
      \hline
      \# & Taxon & Genomes & Name\\\hline
      \input{../query/focal}\\\hline
    \end{tabular}
  \end{center}
\end{table}
#+end_export
#+begin_src bash <<query.sh>>=
  grep -v 511145 focalTaxa.txt |
      while read n taxid ng; do
  	printf "%s\t%s\t" $taxid $ng
  	taxi -t $taxid neidb |
  	    tail -n +2 |
  	    awk '{for(i=3;i<=NF;i++)printf(" %s", $i)}'
  	echo ""
      done |
      cat -n
#+end_src
#+begin_export latex
The next few commands form a ``bridge'' between the accessions and the
phylogeny. If you don't have the resources or the patience to download
the genomes and compute the phylogeny, you can directly skip ahead to
the phylogeny in the next \ty{query.sh} chunk. As a first step on the
bridge, we download the 7361 genomes in \ty{eco.txt}, first in
dehydrated form.
#+end_export
#+begin_src sh <<bridge>>=
  datasets download genome accession \
	   --inputfile eco.txt \
	   --dehydrated
#+end_src
#+begin_export latex
Then we unzip the dehydrated sequences and rehydrate them.
#+end_export
#+begin_src sh <<bridge>>=
  unzip ncbi_datasets.zip
  datasets rehydrate --directory .
#+end_src
#+begin_export latex
Before we construct the phylogeny, we link all genomes into the
directory \ty{all}, which we make.
#+end_export
#+begin_src sh <<bridge>>=
  mkdir all
#+end_src
#+begin_export latex
Like in the pilot, we rename the input files by running
\ty{rename.sh}. This takes about 1.5 minutes.
#+end_export
#+begin_src sh <<bridge>>=
  bash rename.sh
#+end_src
#+begin_export latex
We calculate the pairwise distances from the renamed genomes, convert
them to a neighbor-joining tree, midpoint root the tree, label its
internal nodes, and store it in \ty{eco.nwk}.
#+end_export
#+begin_src bash <<bridge>>=
  phylonium all/* |
      nj |
      midRoot |
      land > eco.nwk
#+end_src
#+begin_export latex
We count the 7,361 complete genomes in \ty{eco.nwk} by picking its
root, node 1, and counting the listed leaves.
#+end_export
#+begin_src sh <<query.sh>>=
  pickle 1 eco.nwk |
      grep -c -v '^#'
#+end_src
#+begin_export latex
Bacterial species are defined as having an ANI distance of at least
95. To check we are dealing only with \emph{E.~coli}, we measure the
largest distance between two taxa in our phylogeny, 0.0391.  This
corresponds to an ANI of 96.1, which fits the species criterion.
#+end_export
#+begin_src sh <<query.sh>>=
  midRoot -p eco2.nwk |
      head -n 1
#+end_src
#+begin_export latex
\begin{verbatim}
# d(562_GCF_057180125.1, 562_GCF_022654545.1): 0.0391
\end{verbatim}

We now query our grand \emph{E. coli} tree for our six focal taxa
listed in Table~\ref{tab:foc} following the order in that table.

\section{\emph{E. coli} O157:H7 (83334)}\label{sec:o157h7}
\input{o157h7}
\section{\emph{E. coli} K-12 (83333)}\label{sec:k12}
\input{k12}
\section{\emph{E. coli} O111:H8 (991910)}\label{sec:o111h8}
\input{o111h8}
\section{\emph{E. coli} O25b:H4-ST131 (941322)}\label{sec:o25bh4}
\input{o25bh4}
\section{\emph{E. coli} O16:H48 (2605619)}\label{sec:o16h48}
\input{o16h48}
\section{\emph{E. coli} O145 (1055538)}\label{sec:o145}
\input{o145}
#+end_export
