#+begin_export latex
We stay in our working directory \ty{tutorial} inside the repo
\ty{ecos}. In Section~\ref{sec:o111h8} we identified all genomes of our
target O111:H8 and placed them in the context of its closest
relatives, the two neighbors shown in Figure~\ref{fig:all}. This means
we can construct markers for the target genomes by identifying the
genome regions that appear in all target genomes that are absent from
the neighbors.

From our \emph{E.~coli} tree we get the 49 genome accessions of the
taxa in Figure~\ref{fig:all}.
#+end_export
#+begin_src sh <<markers.sh>>=
  pickle 5377 eco2.nwk |
      grep -v '^#' |
      sed 's/[^_]*_//' > acc.txt
#+end_src
#+begin_export latex
We download the corresponding genomes.
#+end_export
#+begin_src sh <<markers.sh>>=
  datasets download genome accession \
	   --inputfile acc.txt \
	   --dehydrated \
	   --exclude-atypical
#+end_src
#+begin_export latex
We unzip and rehydrate the downloaded data.
#+end_export
#+begin_src sh <<markers.sh>>=
  unzip ncbi_dataset.zip
  datasets rehydrate --directory .
#+end_src
#+begin_export latex
We rename the genome files on the pattern $<$taxid$>$\_$<$accession$>$
and link them into directory \ty{all} as we did in
Chapter~\ref{ch:p}.
#+end_export
#+begin_src sh <<markers.sh>>=
  mkdir all
  bash rename.sh
#+end_src
#+begin_export latex
We again use the program \ty{fur} for finding the desired unique
genome regions~\cite{hau21:fur,vie24:mar}. So we first construct the
directory of target genomes, \ty{targets}, and then link the target
genomes into it.
#+end_export
#+begin_src sh <<markers.sh>>=
  mkdir targets
  pickle -t 5377 eco2.nwk |
      pickle 5379 |
      grep -v '^#' |
      while read name; do
	  ln -s $(pwd)/all/${name} targets/${name}.fasta
      done
#+end_src
#+begin_export latex
Similarly, we link the neighbors genomes into the directory
\ty{neighbors}.
#+end_export
#+begin_src sh <<markers.sh>>=
  mkdir neighbors
  pickle -t 5377 eco2.nwk |
      pickle -c 5379 |
      grep -v '^#' |
      while read name; do
	  ln -s $(pwd)/all/${name} neighbors/${name}.fasta
      done
#+end_src
#+begin_export latex
We construct the Fur database, \ty{markers.db}. This takes roughly
14\,s on our generic laptop.
#+end_export
#+begin_src sh <<markers.sh>>=
  makeFurDb -t targets -n neighbors -d markers.db
#+end_src
#+begin_export latex
We use \ty{fur} to extract the marker candidates from the Fur
database.
#+end_export
#+begin_src sh <<markers.sh>>=
  fur -d markers.db |
      cleanSeq > markers.fasta
#+end_src
#+begin_export latex
This yields 64\,kb marker candidates, or, if we subtract the remaining
N's, $63732-1248\approx 62$\,kb. This is less than half of the 157\,kb
we found in the pilot study, as our computation now uses twice as many
targets and more closely related neighbors.
#+end_export
#+begin_src sh <<markers.sh>>=
cres markers.fasta
#+end_src
#+begin_export latex
To extract primers from the marker candidates, we convert them to
input for \ty{primers3}, run \ty{primers3}, and save the result in
\ty{markers.prim}.
#+end_export
#+begin_src sh <<markers.sh>>=
  fa2prim markers.fasta |
      primer3_core > markers.prim
#+end_src
#+begin_export latex
We can now extract the primers and their scores from the output of
\ty{primers3}. When we sort them by penalty, we find the best primers
have the low penalty of 0.01.---Not quite as low as the penalty for
the pilot primers, $1.4\times 10^{-4}$, but we expect much better
sensitivity and specificity for the new primer candidates.
#+end_export
#+begin_src sh <<markers.sh>>=
  prim2tab markers.prim |
      sort -n |
      head
#+end_src
#+begin_export latex
\begin{verbatim}
# Penalty  Forward                    Reverse                ...
0.010060   TGTGTACTATTTGCAACGCA       CACATGGCCAGGTATCAAAA   ...
...
\end{verbatim}

We could next quantify the sensitivity and specificity of our primer
candidates using our programs \ty{scop} and \ty{cops}. However, these
require the installation of a large Blast database for reference, so
we skip this step. Primers with sufficient sensitivity and specificity
could then be further tested on a comprehensive DNA database like
\ty{nt} before moving on to \emph{in vitro} testing.
#+end_export
#+begin_export latex
We are finished with marker discovery, so we delete the files we don't
need any more.
#+end_export
#+begin_src sh <<markers.sh>>=
  rm -r all acc.txt md5sum.txt ncbi_dataset \
     ncbi_dataset.zip markers.db markers.prim \
     neighbors README.md targets
#+end_src
